title: Mr. Dall'Oca
description: My personal website for whatever thing I want to say. It seemed a good idea at first.
avatar: /assets/robot.png

theme: jekyll-theme-minimal
gems:
   - jemoji
   - jekyll-seo-tag

repository: MrDallOca/mrdalloca.github.io

